### ISSUE TITLE
Implement Catex Exchange

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1036]
https://www.catex.io/
https://github.com/Catexexchange/api/blob/master/baseCurrency.json
https://www.catex.io/api/token/baseCurrency

**Comment by tmlee** [comment]
https://github.com/catex/catex_exchange_api/wiki

**Comment by tsunami106** [comment]
Kindly list catex on coingenko and good exchange with high volume trade daily

**Comment by wenjieyek** [comment]
I will do this

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/1365
