### ISSUE TITLE
Implement RippleFox Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#107]

**Comment by dominicwong617** [comment]
@tmlee I don't seem to find the API?

**Comment by dominicwong617** [comment]
Or do I have to watch its network?

**Comment by TJ-CoinGecko** [comment]
@tmlee  Ripplefox is basically just a Stellar <-> Ripple exchange, they do this manually where u send the coins manually to their address and hoping that they will send it back to you after that: https://ripplefox.com/util/stellarTag. There is no frontend exchange feature. I think we should not implement as it looks similar to most scams.
