### ISSUE TITLE
Implement Nexybit

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#1189]
https://nexybit.com 
https://github.com/nexybit/openapi/wiki/OpenAPI-Home

**Comment by Swingcloud** [comment]
I will do this

**Comment by TJ-CoinGecko** [comment]
No coin info page

**Comment by bobbyong** [comment]
@TJ-CoinGecko meaning no page to show coin name besides the symbol? 
This is Korean exchange doing trans-fee mining. 

@Swingcloud API all ok I hope?
