### ISSUE TITLE
Implement NebliDex Decentralized Exchange

### ISSUE THREAD

**Issue by david4neblio** [coingecko/cryptoexchange#1192]
Website: https://www.neblidex.xyz
API Docs: https://www.neblidex.xyz/api/

Should be fairly easy to implement into your coin index. Contact me for questions.

**Comment by TJ-CoinGecko** [comment]
No Coin info page

**Comment by TJ-CoinGecko** [comment]
No Coin info page

**Comment by david4neblio** [comment]
@TJ-CoinGecko Coin info page now added to NebliDex at: https://www.neblidex.xyz/listing/

**Comment by tmlee** [comment]
Hi @david4neblio , we are in the process of verifying API results with the actua exchange.
looks like a client is needed to be installed in our machine, that is not something we prefer to do; do you know of other ways we can verify the figures.

**Comment by david4neblio** [comment]
@tmlee The exchange is completely software based (like an electrum wallet). Because it is decentralized and doesn't have centralized order books, the software client handles all orders and there is no one website to view the markets. The API data feed is directly from a connection to one of the decentralized exchange nodes so its updated every 15 minutes.

Probably the best way to run the program, if you are concerned about downloading an application is to use a virtual machine. Thanks tmlee.
