### ISSUE TITLE
Implement Hubi Exchange

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1195]
https://www.hubi.com/
https://www.hubi.com/api/v1/allticker
https://www.hubi.com/other/help/details?id=141&title=Asset%20Introduction&type=0

**Comment by wenjieyek** [comment]
I will do this

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/1199

**Comment by wongy91** [comment]
merged in https://github.com/coingecko/cryptoexchange/pull/1199
