### ISSUE TITLE
Implement BikiCoin Exchange

### ISSUE THREAD

**Issue by ghost** [coingecko/cryptoexchange#1223]
Official Website: https://www.bikicoin.com/index
API documentation: https://github.com/code-bikicoin/bikicoin/blob/master/api/us_en/api_doc_en.md

Tokens Description: https://support.bikicoin.com/hc/en-us/sections/360002197851--recent-activities

**Comment by TJ-CoinGecko** [comment]
https://trade.blocktrade.com/api_documentation/#BlockTrade-API
