### ISSUE TITLE
Implement Saturn Network Exchange

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1233]
https://saturn.network

"curl \
  -i 'https://ticker.saturn.network/api/public/v1/returnTicker.json' \
  -X GET \
  -H ""Content-Type:application/json"" \
  -H 'Accept: application/json' \
  -H ""Origin:coingecko"""

**Comment by magichatsam** [comment]
https://saturn.network
API documentation: https://ticker.saturn.network/
Intro: https://forum.saturn.network/t/getting-started/1998

https://github.com/coingecko/cryptoexchange/issues/1346

**Comment by tmlee** [comment]
https://github.com/coingecko/cryptoexchange/pull/1361
