### ISSUE TITLE
implement Maicoin

### ISSUE THREAD

**Issue by Swingcloud** [coingecko/cryptoexchange#126]
http://developer.maicoin.com/#introduction

I'll do this

**Comment by tmlee** [comment]
@Swingcloud But Maicoin is a brokerage and not an exchange no?

**Comment by Swingcloud** [comment]
Oh, I see, okay I'll close it

**Comment by tmlee** [comment]
@Swingcloud Can implement actually, i just think they wont be publicizing their volume as a broker; or have orderbook or trades later on
