### ISSUE TITLE
Spec must be reliable

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#128]
Currently we are only running integration tests which is a great way to ensure full coverage of the specs.

However, the integration test is not reliable in that 3rd party services may fail and timeout causing test to fail.

Having 3rd party API mocked out may pose as a false positive.

Opening this discussion up for suggestions and ways to improve

**Comment by Swingcloud** [comment]
I think we can use [vcr](https://github.com/vcr/vcr) to log the success respond?

**Comment by tmlee** [comment]
@Swingcloud Yes. I think key thing is to find a way to easily (us maintainers) not forget to update the cassette. 

Here is a draft https://github.com/coingecko/cryptoexchange/pull/131/files

The test seems to be passing well https://travis-ci.org/coingecko/cryptoexchange/builds/281705693

Key part would be to be able to run specs in the following way.
The first one will force expiry on all casettes
```
> VCR=all rspec spec # This will force all casettes to re-record
> rspec spec # This will save a casette if it does not exist, and reuse in the next
```

**Comment by tmlee** [comment]
Implemented VCR and merged into master
