### ISSUE TITLE
Implement Omgfin Exchange

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1317]
https://omgfin.com
https://github.com/omgfin/omfin-rest-api/blob/master/README.md
https://omgfin.com/exchange/article/bitcoin/coininfo

**Comment by dover99** [comment]
waiting to see omgfin in coingecko.

**Comment by omgfin** [comment]
Dear Coingecko,
Could you please update Implement status

thank you very much

**Comment by grtony045** [comment]
CoinGecko always busy with many projects in waiting list. omgfin topic already opened 2 months i think your project will be list soon.

**Comment by grtony045** [comment]
to @TJ-CoinGecko with your growing speed, i think you need hire more staffs in order over take CMC

**Comment by jame8922** [comment]
Among many recent exchangers platform projects. I hope coingecko will pay more attention to projects that have business licenses like omgfin.com. We will need to be more careful with projects that do not have a specific business license in 2019.
