### ISSUE TITLE
Implement VINEX Exchange

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1321]
www.vinex.network
https://docs.vinex.network/api_public_endpoint.html#get-all-markets-info
https://support.vinex.network/hc/en-us/categories/360001358411-Coin-Information

**Comment by wenjieyek** [comment]
I will do this

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/1359
