### ISSUE TITLE
Fix/Update The Rock Trading

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#1355]
https://www.therocktrading.com/
https://api.therocktrading.com/

**Comment by tmlee** [comment]
In reference to https://api.therocktrading.com/doc/v1/index.html#api-Market_API-Tickers
Change the API domain to api.therocktrading.com

There are some changes to the response format.
Particularly volume

**Comment by wenjieyek** [comment]
https://api.therocktrading.com/doc/v1/index.html#api-Market_API-Tickers
this link got 503 error?

**Comment by oromarlb** [comment]
> https://api.therocktrading.com/doc/v1/index.html#api-Market_API-Tickers
> this link got 503 error?

https://twitter.com/TheRockTrading/status/1093420561747841024

There is currently a maintenance going on; the API will be up and running in a few minutes.

**Comment by wenjieyek** [comment]
@oromarlb thanks!

**Comment by oromarlb** [comment]
Maintenance ended, API up and running. Thank you!

**Comment by wenjieyek** [comment]
I will do this
