### ISSUE TITLE
Implement HBUS

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#1356]
https://www.hbus.com/
https://huobi.readme.io/

**Comment by tmlee** [comment]
Use the following API similar to Huobi Global https://github.com/coingecko/cryptoexchange/tree/master/lib/cryptoexchange/exchanges/huobi

Implementation and structure similar, create a copy of it

https://api.huobi.com/v1/common/symbols
https://api.huobi.com/market/detail/merged?symbol=btcusd
