### ISSUE TITLE
Fix Kucoin API with new endpoints

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#1369]
Pair List
https://openapi-v2.kucoin.com/api/v1/symbols

Individual Ticker 
https://openapi-v2.kucoin.com/api/v1/market/stats?symbol=BTT-BTC

Orderbook
https://openapi-v2.kucoin.com/api/v1/market/orderbook/level1?symbol=<symbol>

Since Trade now require authentication, lets deprecate that for now

**Comment by wenjieyek** [comment]
I will do this

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/1370
