### ISSUE TITLE
Implement DACH Exchange

### ISSUE THREAD

**Issue by JinCoinGecko** [coingecko/cryptoexchange#1441]
https://dach.exchange/
https://dach.exchange/pdf/Public_API.pdf

**Comment by wongy91** [comment]
@JinCoinGecko there is no pair endpoint in the API doc.

**Comment by dachcoin** [comment]
@JinCoinGecko 

All pairs with endpoints:

https://dach.exchange/api/public?command=returnTicker&coinPair=DACHX_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=ATHR_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=BTT_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=DASH_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=DGB_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=DLN_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=DOGE_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=KYD_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=LCC_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=LTC_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=SEND_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=SMART_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=TELOS_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=ULG_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=XVG_BTC
https://dach.exchange/api/public?command=returnTicker&coinPair=ZEC_BTC

BG DACH Team

**Comment by JinCoinGecko** [comment]
@dachcoin Sorry but we would like to have an API endpoint that gives us the pairs automatically (eg. https://poloniex.com/public?command=returnTicker)

If we take each pair individually as above, our engineers would have to manually add them in the future when you have new coins.

Thank you

**Comment by dachcoin** [comment]
@JinCoinGecko 
ofcourse, we have also this endpoint:

https://dach.exchange/api/public?command=returnTicker

Please check it and let me know
