### ISSUE TITLE
Update ZB API

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1529]
1)Get all tickers: http://api.zb.cn/data/v1/allTicker
2)Live trading data: http://api.zb.cn/data/v1/ticker?market=btc_usdt
3)Live order book data: http://api.zb.cn/data/v1/depth?market=btc_usdt&size=3

**Comment by wongy91** [comment]
merged in https://github.com/coingecko/cryptoexchange/pull/1532
