### ISSUE TITLE
Update Switcheo Orderbook data

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#1530]
1) All tickers data:  https://docs.switcheo.network/#get-candlesticks for specific trading pairs or https://docs.switcheo.network/#get-last-24-hours for a 24 hour summary
2) Live trading data: for rest use https://docs.switcheo.network/#trades or for websockets use https://docs.switcheo.network/#trade-events
3) Live orderbook data: for rest use https://docs.switcheo.network/#get-offer-book or for websockets use https://docs.switcheo.network/#offer-book

**Comment by wongy91** [comment]
merged in https://github.com/coingecko/cryptoexchange/pull/1532
