### ISSUE TITLE
Implement Allcoin Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#162]
https://allcoin.com/About/API/

- [X] Ticker https://github.com/coingecko/cryptoexchange/pull/163
- [X] Orderbook https://github.com/coingecko/cryptoexchange/pull/163
- [ ] Trades

**Comment by yihyang** [comment]
Hi @tmlee , how can I get started?

**Comment by tmlee** [comment]
Thanks for your interest @yihyang 

We have a guide here at https://github.com/coingecko/cryptoexchange/wiki/Implementing-a-New-Exchange which may be a good place to look at for starters

The following endpoints should be of your interest to implement this https://allcoin.com/About/APIReference/#SpotPriceAPI

**Comment by yihyang** [comment]
ok noted, I will take on this task

**Comment by yihyang** [comment]
@tmlee here you go https://github.com/coingecko/cryptoexchange/pull/163

**Comment by tmlee** [comment]
@yihangho Thanks for your contribution

In the documentation https://allcoin.com/About/APIReference/#SpotPriceAPI
Their orderbook API is known as `depth` 
eg. `https://api.allcoin.com/api/v1/trades?since=5000&symbol=ltc_usd`

And trades is as below ` https://api.allcoin.com/api/v1/trades?since=5000`

We have not implemented Trading/Account API yet which requires API token. So we are not sure how to structure that yet at the moment.

**Comment by yihyang** [comment]
@tmlee I have added the Orderbook for `AllCoin` here: https://github.com/coingecko/cryptoexchange/pull/163/commits/b37763bab81cde0e6be6969c7e4b42e995311054

**Comment by aydinozkan** [comment]
Hi,

Is there any `coin status` provided by your api. For example, Ticker service returns value for `BFDT`coin but both Deposit and Withdrawal are disabled for it.
