### ISSUE TITLE
Platform information in token

### ISSUE THREAD

**Issue by ellis2323** [coingecko/cryptoexchange#1623]
Many tokens like Maker, BAT are implemented on the ethereum platform. It could be great to provide this information like coinmarket does.
In their API, they export a platform information with the chain (ethereum, eos, ...) and the address of the smart contract which implements it. The address is unique and more reliable than a symbol or a name to identity it.

**Comment by Lalu-Purwadi** [comment]
@purwadi

**Comment by ellis2323** [comment]
you can find it with a get /coins/{id}. It's a call by coin. So do it once and cache it.
