### ISSUE TITLE
Error should be propagated

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#165]
Currently when there is an exception thrown, we catch in and return a generic error like "Not available"

This is not descriptive enough, while we should catch it. Perhaps we should return our own class of errors. or at the very least propagate some of the information from the actual exception.

**Comment by jimmynguyc** [comment]
I can take a look at this. I do see `rescue HTTP::ConnectionError, HTTP::TimeoutError, JSON::ParserError` already implemented for HTTP connectivity issues. Where do you want to implement this better error description?

**Comment by tmlee** [comment]
@jimmynguyc I am open to suggestion. 
Think what we currently have now is a rescue all and returning a generic error like https://github.com/coingecko/cryptoexchange/blob/cebef44ced05d1c5dbf428eff25b07f1a53806c2/lib/cryptoexchange/client.rb#L12

As the gem user myself, this is obscure and there is little information about why the error is thrown, because it can be a HTTP error or perhaps the API returns unexpected value.

Not concrete, but my thoughts are (1) removing the rescue and let the exception be thrown (but we will get exception with different class names) or (2) create a set of pre-defined exception classes and throw that instead.

What are your thoughts?

**Comment by tmlee** [comment]
We have implemented an error specific thrown
