### ISSUE TITLE
Implement EXMO Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#181]
Docs at https://exmo.com/en/api

**Comment by falkoner** [comment]
Let me try to do this one.

**Comment by tmlee** [comment]
Awesome thanks @falkoner 
https://api.exmo.com/v1/ticker/ for Ticker
https://api.exmo.com/v1/trades/?pair=BTC_USD for Trades
https://api.exmo.com/v1/order_book/?pair=BTC_USD for Orderbook
I think you can use the Ticker API or https://api.exmo.com/v1/pair_settings/ to get the list of supported pairs whichever appropriate
