### ISSUE TITLE
Implement Coss Ticker, OrderBook, and Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#185]
https://exchange.coss.io/api/ticker

**Comment by VijayGomathi** [comment]
can you brief me about this

**Comment by tmlee** [comment]
Hi @VijayGomathi 
Currently I am only able to acquire the API for Ticker, so perhaps we can only implement Ticker for now.
These guides may be useful to you to start https://github.com/coingecko/cryptoexchange/blob/master/CONTRIBUTING.md
and especially https://github.com/coingecko/cryptoexchange/wiki/Implementing-a-New-Exchange

**Comment by tmlee** [comment]
Implemented ticker at https://github.com/coingecko/cryptoexchange/pull/229/files
No orderbook and trades API available
