### ISSUE TITLE
Implement OpenLedger DEX Exchange Ticker, OrderBook, and Trades 

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#208]
https://openledger.io/

**Comment by bobbyong** [comment]
Here is details for api and links: 

List of Assets:
Get list of available assets to iterate over for requesting statistical data using other methods.
Updated every 5 minutes.
Request: GET /api/asset/list
Response:
[
    string, // code of asset
    …
]
URL: https://stats.openledger.info/api/asset/list


—
List of Pairs:
Get list of trading pairs with last price and 24h volume. 
List is sorted from high to low volume and does not include pairs with zero volume from last 24 hours.
Updated every 5 minutes.
Request: GET /api/asset/pairs
Response:
{
    "FOO_BAR": {
        "baseName":    "FOO",
        "quoteName":   "BAR",
        "last":        57375.77648952665,
        "baseVolume":  1090785.0098999974,
        "quoteVolume": 18.984800210000024,
        "usdVolume":   158329.73291707004,
        "btsVolume":   1089267.653547327
    },
    ...
}
URL: https://stats.openledger.info/api/asset/pairs

**Comment by bobbyong** [comment]
List of Assets:
Get list of available assets to iterate over for requesting statistical data using other methods.
Updated every 5 minutes.
Request: GET /api/asset/list
Response:
[
    string, // code of asset
    …
]
URL: https://stats.openledger.info/api/asset/list
—
List of Pairs:
Get list of trading pairs with last price and 24h volume. 
List is sorted from high to low volume and does not include pairs with zero volume from last 24 hours.
Updated every 5 minutes.
Request: GET /api/asset/pairs
Response:
{
    "FOO_BAR": {
        "baseName":    "FOO",
        "quoteName":   "BAR",
        "last":        57375.77648952665,
        "baseVolume":  1090785.0098999974,
        "quoteVolume": 18.984800210000024,
        "usdVolume":   158329.73291707004,
        "btsVolume":   1089267.653547327
    },
    ...
}
URL: https://stats.openledger.info/api/asset/pairs

**Comment by Swingcloud** [comment]
let me do this

**Comment by Swingcloud** [comment]
@bobbyong  seems there's some pairs don't show on the openledger.io but you can still use url like 
https://openledger.io/market/unknown.BRIDGE.ROE_unknown.BRIDGE.BTC
to get the exchange value on this pair 
```ruby
"BRIDGE.BTC_BRIDGE.ROE": {
  "baseName": "BRIDGE.BTC",
  "quoteName": "BRIDGE.ROE",
  "last": 0.00001053000000004731,
  "baseVolume": 0.16442883,
  "quoteVolume": 14303.205994,
  "usdVolume": 1654.2511415772044,
  "btsVolume": 4518.522642469271
}
```
and in the list api didn't show this two assets, so maybe we just use this pair api to grab all list exchange, or we take that exchange and match the assets list, if the asset is not in the list, then we skip implement that pair?

**Comment by Swingcloud** [comment]
They update api!! so I will use this to implement it

List of Pairs - https://stat-api.openledger.info/api/asset/pairs - List is sorted from high to low volume and does not include pairs with zero volume from last 24 hours.
List of Markets - https://stat-api.openledger.info/api/v1/markets - List is not sorted. It does not include markets with zero volume from last 24 hours.
Trade History - https://stat-api.openledger.info/api/v1/trades?market=LTC_BTC - Get list of last trades for given market. Current limit is 100 last items in the history.
Order Book - https://stat-api.openledger.info/api/v1/orderbook?market=XCEL_BTC - Get list of current open orders for given market.
Ticker - https://stat-api.openledger.info/api/v1/ticker?market=XCEL_BTC - Get ticker of given market.
