### ISSUE TITLE
Implement Coinegg Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#277]
https://www.coinegg.com/explain.api.html

**Comment by Swingcloud** [comment]
I'll do this

**Comment by Swingcloud** [comment]
seems there are two target coins, but api endpoint can't change target coin, so I asked them, here is their reply:
```
Now there's only a BTC trading zone in API for the time being
```
so I will add btc pairs for now
