### ISSUE TITLE
lykke volume is incorrect

### ISSUE THREAD

**Issue by mmplisskin** [coingecko/cryptoexchange#290]
Lykke is displaying the wrong base pairs volume

BTC / USD  720,401.34

**Comment by Swingcloud** [comment]
sorry @mmplisskin our volume on ticker is defined by the base currency, and if we found that the volume of respond is in target, we will take `last` price to divide it, so maybe it's not what you saw in the respond

**Comment by mmplisskin** [comment]
Ah interesting it seems to be working properly now, there could have been an issue with the exchange. Sorry about that.
