### ISSUE TITLE
Implement Upbit Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#306]
https://upbit.com/

**Comment by infinitytn** [comment]
https://crix-api-endpoint.upbit.com/v1/crix/candles/@PeriodType@/@Period@?code=CRIX.UPBIT.@Market@-@Ticker@&count=@DataNumber@&to=@TimeStamp@


parameter names

@PeriodType@
@Period@
@Market@
@Ticker@
@DataNumber@
@TimeStamp@


PeriodType: minutes, days, weeks, months (there is no hours)
Period: 1, 3, 5, 10, 15, 30, 60, 240 (only in minutes)
Market: KRW, BTC, ETH, USDT
Ticker: BTC, ETH, XRP, STEEM, SBD ...etc Upbit ticker
DataNumber: 1(default), 2, 3, 4 (you need to test what this shows)
TimeStamp: UTC timezone based the TimeStamp that you want to get the price.

example.

BTC/KRW 10 minutes chart. last 2 data set (timestamp: 2017-12-27 05:10:00 UTC)
https://crix-api-endpoint.upbit.com/v1/crix/candles/minutes/10?code=CRIX.UPBIT.KRW-BTC&count=2&to=2017-12-27%2005:10:00

BTC/KRW 4 hours chart. last 1 data set (timestamp: current)
https://crix-api-endpoint.upbit.com/v1/crix/candles/minutes/240?code=CRIX.UPBIT.KRW-BTC

SBD/BTC 1 day chart. last 3 data set (timestamp: current)
https://crix-api-endpoint.upbit.com/v1/crix/candles/days?code=CRIX.UPBIT.BTC-SBD&count=3

STEEM/BTC 1 week chart. last 1 data set (timestampe: current)
https://crix-api-endpoint.upbit.com/v1/crix/candles/weeks?code=CRIX.UPBIT.BTC-STEEM

ETH/BTC 1 month chart. last 5 data set (timestamp: 2017-12-20 00:00:00 UTC)
https://crix-api-endpoint.upbit.com/v1/crix/candles/months?code=CRIX.UPBIT.BTC-ETH&count=5&to=2017-12-20%2000:00:00

**Comment by infinitytn** [comment]
the api is unofficial but it is from the official website. upbit created api already for the price chart but they are using it only for their mobile applications. and they did not release the info to public.

**Comment by estherleongym** [comment]
Working on this.
