### ISSUE TITLE
Implement cfinex Ticker, Orderbook, Trades 

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#332]
https://alcurex.com/

**Comment by Swingcloud** [comment]
I'd asked them if they have api doc or not

**Comment by bobbyong** [comment]
Alcurex just changed ownership to Cfinex: https://cfinex.com
So no need to implement for alcurex but do straight for cfinex
can you help check if there are api docs can implement alr?

**Comment by bobbyong** [comment]
https://cfinex.com/api/tickerapi
https://cfinex.com/api/help

**Comment by Swingcloud** [comment]
cool! let me do it!
