### ISSUE TITLE
Implement Waves Decentralized Exchange Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#340]
http://www.wavesplatform.com/

**Comment by Swingcloud** [comment]
https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API 
Let me do this

**Comment by Swingcloud** [comment]
https://github.com/wavesplatform/Waves/issues/854

according to this issue from Waves, seems they don't have ticker data in api currently, so need to wait form them to reply this issue first

**Comment by bobbyong** [comment]
@Swingcloud they just emailed us and now have API here:
http://marketdata.wavesplatform.com/

Let's proceed to implement this

**Comment by Swingcloud** [comment]
got it!
