### ISSUE TITLE
Implement B2BX Ticker, Orderbook, and Trades 

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#346]
https://live.b2bx.exchange/
https://www.b2bx.exchange

API: https://live.b2bx.exchange/tradeapi
https://live.b2bx.exchange/websocketfeedapi
https://live.b2bx.exchange/websockettradeapi

**Comment by bobbyong** [comment]
https://cryptottlivewebapi.b2bx.exchange:8443/api/v1/public/ticker

**Comment by estherleongym** [comment]
I'll take this

**Comment by estherleongym** [comment]
keep getting an error `#<HTTP::Response/1.1 415 Unsupported Media Type {"Content-Length"=>"0", "Server"=>"Microsoft-HTTPAPI/2.0", "Date"=>"Sat, 04 Aug 2018 15:47:03 GMT", "Connection"=>"close"}>` when calling API endpoints from gem, but it works in browser and Postman. 

I've tried setting the following but to no avail: 

`HTTP.headers("Content-Type" => "application/json; charset=utf8", "Content-Encoding" => "gzip", :accept => "application/json").get("https://cryptottlivewebapi.b2bx.exchange:8443/api/v1/public/ticker")`

**Comment by estherleongym** [comment]
@Swingcloud Thanks Sam!! `HTTP.use(:auto_inflate).headers("Accept-Encoding" => "gzip").get("https://cryptottlivewebapi.b2bx.exchange:8443/api/v1/public/ticker")` worked!
