### ISSUE TITLE
Implement ForkDelta Ticker

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#347]
https://forkdelta.github.io/

**Comment by tmlee** [comment]
API call at https://api.forkdelta.com/returnTicker
Map the list with https://forkdelta.github.io/config/main.json
Not too straightforward

**Comment by tmlee** [comment]
To do this, would be
1. Fetch the list of pairs from returnTicker, get the 0x address and map it against main.json
2. MarketPair will store the SYMBOL instead of 0x
3. Use SYMBOL to map to main.json which in turn searches the ticker in the api result using 0x

**Comment by cySheng** [comment]
Working on this!
