### ISSUE TITLE
Implement Bits Blockchain Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#355]
https://bitsblockchain.com/

**Comment by estherleongym** [comment]
https://www.bitsblockchain.net/moon/v1/market/tick/ANX/LTCBTC

https://www.bitsblockchain.net/api/v1/stats/ATMCEUR/history/1440?from=1396451997&to=1520868057&tz=Asia%2FTaipei

https://www.bitsblockchain.net/moon/v1/market/topOrderBook/ANX/BTCEUR

**Comment by estherleongym** [comment]
will work on this
