### ISSUE TITLE
Implement Cryptohub Ticker, Orderbook, Trades 

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#364]
https://cryptohub.online

**Comment by startsts** [comment]
Hi, I'm dev of CryptoHub.
Our ticker API is here https://cryptohub.online/api/market/ticker/
It has same format as poloniex exchange.
Trading API doesnt exist yet.

**Comment by Swingcloud** [comment]
I will do this

**Comment by startsts** [comment]
@Swingcloud CryptoHub has only ticker api currenty.  no api for order book or trading
