### ISSUE TITLE
Implement Coinhub Ticker, Orderbook, Trades 

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#369]
https://www.coinhub.io/gateway/coinhub/public/returnTicker

**Comment by estherleongym** [comment]
API endpoints returning error message; reached out to Coinhub to verify.

**Sample:** https://www.coinhub.io/api#!/exchange.json/chart

**Request sent**: `https://www.coinhub.io/gateway/public/chart?market="ETH-USD"&openIntervals	=true`

**Response returned**: `{"success":false,"missing_authenticators":[],"infos":[],"warnings":[],"errors":[{"JSON_DECODE_FAILED":["No error"]}],"results":{}}`

**Comment by Swingcloud** [comment]
let me do this

**Comment by estherleongym** [comment]
I'll take this, discussed with @Swingcloud already

**Comment by TJ-CoinGecko** [comment]
Provided by coinhub: https://www.coinhub.io/api#/cnh
