### ISSUE TITLE
Implement Crex24 Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#378]
https://crex24.com/

**Comment by Swingcloud** [comment]
https://crex24.com/trade-api
I'll do this

**Comment by vitorgamer58** [comment]
and https://api.crex24.com/CryptoExchangeService/BotPublic/ReturnTicker to return all tickets

**Comment by Swingcloud** [comment]
thank you @vitorgamer58
