### ISSUE TITLE
Implement Ticker, Orderbook, and Trades for CPDAX

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#398]
https://www.cpdax.com/static/etc-pages/api.html

**Comment by tmlee** [comment]
Use the detailed API for ticker https://api.cpdax.com/api/v1/ticker/{currency_pair}/detailed
and the tickers for currency list

**Comment by wenjieyek** [comment]
i will do this

**Comment by tmlee** [comment]
https://github.com/coingecko/cryptoexchange/pull/512
