### ISSUE TITLE
Implement Trade.mn Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#399]
1. Ticker : General information
URL : https://api.trade.en/public/ticker/{currency} 

2. Order book : current active orders
URL :https://api.trade.en/public/orderbook/{pair}

3. Recent transactions
URL :https://api.trade.en/public/recent_transactions/{pair}

**Comment by estherleongym** [comment]
Will take this
