### ISSUE TITLE
Implement Kyber Network Protocol Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#408]
website: https://kyber.network/
 https://github.com/KyberNetwork/smart-contracts/blob/ropsten/web3deployment/ropsten.json

**Comment by andrewsource147** [comment]
Please refer to link https://docs.google.com/document/d/1WvMQa1FyshBzMRIULRHPxEGlLL0gmM9PS0vKa8Jfnf0/edit

**Comment by tmlee** [comment]
Great, i'll work on this one
