### ISSUE TITLE
Implement BitShares Asset Exchange Protocol Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#423]

**Comment by Swingcloud** [comment]
this maybe the api doc 
http://docs.bitshares.org/api/

**Comment by tmlee** [comment]
Lets use this API by http://cryptofresh.com/api/docs

Track BTS target only for now
https://cryptofresh.com/api/asset/markets?asset=BTS

**Comment by Swingcloud** [comment]
👌

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/1366
