### ISSUE TITLE
OKex API for pairs

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#452]
Use this unofficial API call for currency list okex
https://www.okex.com/v2/spot/markets/currencies

permute base against target for BTC, ETH, BCH, and USDT

**Comment by Swingcloud** [comment]
let me do this

**Comment by Swingcloud** [comment]
@tmlee seems there has better option to implement this, should I use this? 
https://www.okex.com/v2/markets/products
or use the one you provide?
