### ISSUE TITLE
Implement Bitrue Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#462]
website: https://www.bitrue.com/exchange-web/index.html

**Comment by tmlee** [comment]
@TJ-CoinGecko Cant seem to find the API docs

**Comment by bobbyong** [comment]
use this: https://www.bitrue.com/kline-api/public.json?command=returnTicker

**Comment by bobbyong** [comment]
@Swingcloud can you take this?
