### ISSUE TITLE
Implement BiteBTC Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#468]
website:  https://bitebtc.com/
https://bitebtc.com/api

**Comment by bitebtc** [comment]
We'll highly appreciate implementation of our ticker, orderbook and trades!

**Comment by Swingcloud** [comment]
I'll do this

**Comment by bitebtc** [comment]
Thank you for your kind assistance!
