### ISSUE TITLE
Implement BitHash Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#470]
website: https://www.bithash.net
https://github.com/bithash-exchange/bithash-exchange-api

**Comment by Swingcloud** [comment]
seems this is so easy to reach limit ( even I just in implementation and call less than 10 calls during an hour, and I got a warning)
maybe will implement later

**Comment by Swingcloud** [comment]
they reply, seems there's some upgrade about their api
```
There has been an upgrade recently which could temporary cause such an error. That one is fixed now. You are free to use those methods - they are public and do not require any privileges.
 
Also, we would like to note of the correct usage of vol/vol_cur values:
 
vol_cur = Trading Volume
vol = Trading Value
 
Example:
 
vol_cur -> BTC/USD <- vol
 
Feel free to contact us any time if you need any assistance.
```
and need to use `vol_cur` in bae vol
