### ISSUE TITLE
Implement Cryptex Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#476]
https://cryptex.net/api/v1/btc_usd/ticker
https://cryptex.net/api/v1/btc_usd/orderbook
https://cryptex.net/api/v1/btc_usd/trades

**Comment by Swingcloud** [comment]
I'll do this

**Comment by Swingcloud** [comment]
seems there is LTC_USD as well, will implement that too
