### ISSUE TITLE
Implement KoinOK Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#491]
website: koinok.com
https://docs.google.com/document/u/1/d/e/2PACX-1vRG7STG6K5PAzCjknjvpo7jtbrl_R-arJbQmBKIPZbhRLxetpA6932bwKajVepY_Yl8GnZ3dd03aG7x/pub

**Comment by wenjieyek** [comment]
i will do this!
