### ISSUE TITLE
Implement CoinJar Exchange ticker, orderbook, and trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#540]
Docs at https://docs.exchange.coinjar.com/data-api/#/reference/products/ticker

pairs: https://api.exchange.coinjar.com/products
ticker: https://data.exchange.coinjar.com/products/<id>/ticker
orderbook and trades
https://docs.exchange.coinjar.com/data-api/#/reference/products/product/order-book
https://docs.exchange.coinjar.com/data-api/#/reference/products/product/trades

**Comment by wenjieyek** [comment]
I do this

**Comment by wenjieyek** [comment]
#547
