### ISSUE TITLE
Implement Bilaxy Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#548]
Doc at https://bilaxy.com/api#interface

Use http://api.bilaxy.com/v1/tickers to map against pairs, but pairs represented in `id` of https://bilaxy.com/api#symbols

**Comment by Swingcloud** [comment]
Will do this

**Comment by Swingcloud** [comment]
@tmlee  seems they use id to fetch ticker info, can I use yml file to fetch paris info and add an attribute about `id` on `market_pair`?

**Comment by tmlee** [comment]
Yeah, lets go with that. 

the `id` can be added to the MarketPair subclass. No need to add that to the parent.
