### ISSUE TITLE
Implement Kryptono Ticker

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#549]
Using unofficial API
Exchange: https://kryptono.exchange/k/accounts/trade?s=EOS_BTC

Following API (one of it can be used)
https://engine.kryptono.exchange/api/v1/dp?symbol=EOS_BTC
https://engine.kryptono.exchange/api/v1/cs?symbol=EOS_BTC&tt=1m
https://engine.kryptono.exchange/api/v1/ht?symbol=EOS_BTC

**Comment by bobbyong** [comment]
Official API from founder: https://bitbucket.org/blockchainuts/volume_api/src/master/

**Comment by Swingcloud** [comment]
I'll do it

**Comment by tmlee** [comment]
@bobbyong that API looks like a csv rather than a direct data response

**Comment by tmlee** [comment]
Merged and using the unofficial API for now
