### ISSUE TITLE
Check if the volume are assigned correctly

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#56]
The volume under Ticker should refer to the base currency. Need to check all existing implementation exchanges if that value is correct.

**Comment by tmlee** [comment]
List of exchanges, verified volume assigned correctly

- [/] anx
- [/] bitcoin_indonesia
- [/] bitflyer
- [] bithumb
- [/] bitstamp
- [/] bittrex

...

**Comment by tmlee** [comment]
@dominicwong617 @Swingcloud Could you double confirm for the exchanges you have implemented if the `volume` is assigned correctly? That is it should be the `base`.

Other than the exchanges that i mentioned above, and after checking it. just comment and list them here if they are good? So i can double check the remainder

**Comment by Swingcloud** [comment]
will do today @tmlee

**Comment by Swingcloud** [comment]
checked: 
- /anx
- /bitcoin_indonesia
- /bitfinex
- /bitflyer
- /bithumb
- /bitstamp
- /bittrex
- /bleutrade (wrong, WIP)
- /btcc
- /bter
- /ccex
- /coin_exchange (wrong, WIP)
- /coincheck
- /coinone
- /cryptopia (wrong, WIP)
- /ether_delta (wrong, WIP)
- /gatecoin 
- /gdax
- /gemini
- /hitbtc
- /korbit
- /kraken
- /lakebtc
- /liqui
- /livecoin
- /novaexchange ( doesn't check yet since server maintain)
- /okcoin
- /poloniex
- /quoine
- /yobit

**Comment by Swingcloud** [comment]
I fix this on #68

**Comment by dominicwong617** [comment]
@Swingcloud Thank you for checking for me as well 👏  👏  👏

**Comment by Swingcloud** [comment]
the latest check list 
- [x] anx
- [x] bitcoin_indonesia
- [x] bitfinex
- [x] bitflyer
- [x] bithumb
- [x] bitstamp
- [x] bittrex - use Volume
- [x] bleutrade - use Volume
- [x] btcc
- [x] bter
- [x] ccex
- [x] chbtc
- [x] coin_exchange
- [x] coincheck
- [x] coinone
- [x] cryptopia - use Volume
- [x] ether_delta - use quoteVolume
- [x] gatecoin
- [x] gdax
- [x] gemini
- [x] hitbtc
- [x] jubi
- [x] korbit
- [x] kraken
- [x] lakebtc - correct
- [x] liqui - correct
- [x] livecoin - correct
- [x] novaexchange - correct
- [x] okcoin - correct
- [x] poloniex - use quoteVolume
- [x] quoine - correct
- [x] viabtc - correct
- [x] yobit - correct
- [x] yunbi - correct

**Comment by dominicwong617** [comment]
@tmlee closing this issue
