### ISSUE TITLE
Implement Miami Crypto Exchange Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#571]
www.miami.exchange
https://cerberus.mercury.cash/public/ticker

**Comment by Swingcloud** [comment]
let me do this

**Comment by Swingcloud** [comment]
seems the ticker endpoint said this is cerberus mercury exchange not miami, and I searched for miami exchange's API and it said it's under construction, so should I just implement this as miami exchange? @TJ-CoinGecko

**Comment by TJ-CoinGecko** [comment]
@Swingcloud  Hi, seems that they are both from the same company, but the miami crypto exchange is yet to go live, and the api seems to not be returning the intended result. I will close this issue for now. Sorry about that.
