### ISSUE TITLE
Implement Orderbook.io Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#575]
Orderbook.io
https://drive.google.com/file/d/1fhBoFGazFZUlMhQwRTZYAeQACLP2hqLL/view?usp=sharing

**Comment by TJ-CoinGecko** [comment]
[coingecko.zip](https://github.com/coingecko/cryptoexchange/files/2071328/coingecko.zip)

**Comment by estherleongym** [comment]
I'll take this
