### ISSUE TITLE
Implement BTCChina Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#60]

**Comment by Swingcloud** [comment]
I think this one is the same as `BTCC` one? in Btcc have usd to btc and cny to b2c, should we split it?

**Comment by tmlee** [comment]
It looks like the cny pair isnt up to date https://pro-data.btcc.com/data/pro/ticker?symbol=XBTCNY
In my view, it appears that what's working are BTCC for USD pair and BTCChina for CNY pair.

**Comment by Swingcloud** [comment]
so I will delete btc_cny url in btcc

**Comment by tmlee** [comment]
Althought BTCChina is down now, but it may someday return.
Is BTCC different than BTCChina?
The market is down now, but the last captured price is different
Documentation at https://www.btcchina.com/apidocs/spot-exchange-market-data-rest-api-zh.html

Compare https://data.btcchina.com/data/ticker?market=btccny vs https://pro-data.btcc.com/data/pro/ticker?symbol=XBTCNY

**Comment by TJ-CoinGecko** [comment]
#677
