### ISSUE TITLE
Implement C-PATEX Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#634]
www.c-patex.com
https://c-patex.com/documents/api_v2   
https://c-patex.com/documents/websocket_api

**Comment by Swingcloud** [comment]
let me do this

**Comment by OTC-Buyer** [comment]
I am confused. Is this completed or not? Ticket 688 (merged) says 3 of 3 tasks complete, so does that mean C-PATEX has been integrated into CoinGecko as a listed exchange? I do not see it currently listed as an exchange though.  (Heads up dev of C-PATEX recently submitted form to get added but never received a ticket number for it. It might be in back end somewhere which will need to be merged with this ticket too I assume. It may have more needed info too for you to implement.)

**Comment by tmlee** [comment]
Hi @OTC-Buyer I will look into this issue internally for CoinGecko addition side of things.

To clarify, merger into this library does not equal to listing on CoinGecko.
This library is an open source project as such anyone using this is free to decide which exchanges to add; and CoinGecko is one of the active contributor and user of this library itself.

**Comment by OTC-Buyer** [comment]
Sweet I see it added on CoinGecko now, thanks ... but where does information for the coin name and logo get pulled from so I can help the exchange or someone else fix that for us since it shows question marks on some? Thanks in advance.
