### ISSUE TITLE
Use /markets to pull pairs automatically from RadarRelay

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#669]
https://developers.radarrelay.com/data-tutorial

We currently use .yml to list pairs on Radar Relay. The new /markets endpoint looks like something we can use to automate the pairs list

**Comment by Swingcloud** [comment]
let me look at it

**Comment by wenjieyek** [comment]
I'll do this

**Comment by wenjieyek** [comment]
I'll do this

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/682
