### ISSUE TITLE
Implement Stocks.exchange new API

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#678]
Old API is broken now
New API for http://help.stocks.exchange/api-integration/public-api
Updating https://github.com/coingecko/cryptoexchange/tree/master/lib/cryptoexchange/exchanges/stocks_exchange

**Comment by Swingcloud** [comment]
let me work on this

**Comment by Swingcloud** [comment]
just check on this api and found all api works fine
about pair one 
https://app.stocks.exchange/api2/markets

and ticker one
https://app.stocks.exchange/api2/ticker 
seems all good @tmlee

**Comment by Swingcloud** [comment]
just check on this api and found all api works fine
about pair one 
https://app.stocks.exchange/api2/markets

and ticker one
https://app.stocks.exchange/api2/ticker 
seems all good @tmlee

**Comment by tmlee** [comment]
Resolved at this commit https://github.com/coingecko/cryptoexchange/commit/7ac1d1f0a4b9f33567529052be71982e9462d269#diff-44f42771de2a211aca22173ea3001e36
