### ISSUE TITLE
Fix API_URL for bitflyer and coincheck market.rb

### ISSUE THREAD

**Issue by Merlz** [coingecko/cryptoexchange#70]
There is a trailing slash in two of the exchange::{name}::market.rb files that need to be removed otherwise complete url will include a double slash:
****************
NAME = 'bitflyer'
API_URL = 'https://api.bitflyer.jp/v1/'

NAME = 'coincheck'
API_URL = 'https://coincheck.com/api/'

**Comment by dominicwong617** [comment]
@Merlz let me take a look at it.

**Comment by dominicwong617** [comment]
@Merlz it's been fixed.
