### ISSUE TITLE
Implement Coindeal Exchange Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#737]
https://coindeal.com
https://apigateway.coindeal.com/api/doc

**Comment by bobbyong** [comment]
https://coindeal.com/info-api

**Comment by co0lsky** [comment]
I'll work on this

**Comment by co0lsky** [comment]
They don't have a date. I will work on the other exchange first.

<img width="818" alt="screen shot 2018-09-19 at 9 44 23 pm" src="https://user-images.githubusercontent.com/1111529/45757119-37d8d780-bc55-11e8-8f08-9c4402942d50.png">
