### ISSUE TITLE
Implement Instant Bitex Limited Exchange Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#743]
https://instantbitex.com
https://instantbitex.com/api

**Comment by estherleongym** [comment]
I'll take this

**Comment by Instantbitex** [comment]
Can you push This

**Comment by Instantbitex** [comment]
Hi  estherleongym can you please Pull this

**Comment by estherleongym** [comment]
@Instantbitex apologies, will push this tonight.

**Comment by Instantbitex** [comment]
@estherleongym thank you so much
