### ISSUE TITLE
Implement DOBI Trade Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#750]
https://www.dobitrade.com/
https://api.dobitrade.com/

**Comment by avana-sky** [comment]
I'll start to work on this.

**Comment by co0lsky** [comment]
I'll start to work on this

**Comment by co0lsky** [comment]
## API URL
https://api.dobitrade.com

## Endpoints
- pair - /trade/markets (under Trading API > Trading market)
- trade - /market/quote (under Quotes API > Latest Quotes)
- order book - /market/orderbook (under Quotes API > Order book)

**Comment by co0lsky** [comment]
Unable to create secret key nor add whitelist IP

<img width="1164" alt="screen shot 2018-08-11 at 7 32 05 am" src="https://user-images.githubusercontent.com/1111529/43985365-7725aa70-9d39-11e8-8547-21016bda9295.png">

I've sent an email to dobitrade to check about it. Waiting for their reply.

By any chance, do you already have the account and secret key created?

@TJ-CoinGecko @tmlee

**Comment by co0lsky** [comment]
Unable to add whitelist IP to my API account

<img width="1164" alt="screen shot 2018-08-11 at 7 32 05 am" src="https://user-images.githubusercontent.com/1111529/43985479-48ab5b3a-9d3a-11e8-9a2e-eda6ad87f0f7.png">

I've sent an email to dobitrade to check about this. Waiting for the reply.

By any chance, do you have an account and can whitelist my IP?

@TJ-CoinGecko @tmlee
