### ISSUE TITLE
Implement DragonEX Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#755]
https://dragonex.io/
https://github.com/Dragonexio/OpenApi/tree/master/docs

**Comment by Swingcloud** [comment]
let me do this

**Comment by bobbyong** [comment]
@Swingcloud how is this coming along? 
do let me know if there is any issue. thank you

**Comment by Swingcloud** [comment]
seems no issue :bow: will finish today

**Comment by tmlee** [comment]
@Swingcloud Reopening this issue because i think `https://openapi.dragonex.io/api/v1/market/real/?symbol_id=99` is a better option for Ticker rather than Kline

Current Kline is not correct calculation for volume so its better to just use Ticker to get the correct data directly

**Comment by tmlee** [comment]
Refer to Section "Query real time quotes" under https://github.com/Dragonexio/OpenApi/blob/master/docs/English/1.interface_document_v1.md

**Comment by tmlee** [comment]
@Swingcloud
