### ISSUE TITLE
Implement CoinEx Market Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#766]
https://www.coinexmarket.io/
http://api.coinexmarket.io/

**Comment by nomanurrehman** [comment]
I am working on this one.

**Comment by nomanurrehman** [comment]
Can someone confirm if it is possible to work on this one?

The documentation states different responses than what is returned.

For example, the history call returns

```javascript
{"status":1,"message":"Success","data":[{"id":"13","vendor":"ETH","market":"BTC","coins":"28.0000000000","coincost":"13.4890000000"},{"id":"7681","vendor":"ETH","market":"BTC","coins":"0.9650000000","coincost":"14.1906000000"},{"id":"7779","vendor":"ETH","market":"BTC","coins":"0.8460000000","coincost":"14.1906000000"},{"id":"7905","vendor":"ETH","market":"BTC","coins":"0.1590000000","coincost":"14.1906000000"},{"id":"7696","vendor":"ETH","market":"BTC","coins":"0.8790000000","coincost":"14.1902000000"}]}
```

And the documentation says.

```javascript
{
	"result": "true",
        "data": [
            {
                "tradeID": "27734287",
                "date": "2017-09-29 11:52:05",
                "timestamp": "1506657125",
                "type": "buy",
                "rate": 0.1,
                "amount": 0.01,
                "total": 0.001
            }
        ],
        "elapsed": "6.901ms"
  }
```

Fetching tickers takes forever and times out.

I am also having trouble mapping fields returned by history call.

**Comment by nomanurrehman** [comment]
@estherleongym Even a simple HTTP.get fails from the Ruby console.

I am droping this one since something seems broken about it.

**Comment by bobbyong** [comment]
@estherleongym when you have time, do kindly take over here to see if you can implement this. thank you.

**Comment by estherleongym** [comment]
@bobbyong ok, sure!

**Comment by estherleongym** [comment]
@bobbyong turns out I've completed this exchange under Issue #633

**Comment by coinexmarket** [comment]
Hello team,

we are updated with the bug fix and performance optimizations. 

can you check them with the updates and complete integration process.

here are the sample links.
http://api.coinexmarket.io/tradeHistory/BTT_BTC
http://api.coinexmarket.io/orderBook/BTT_BTC

Thanks
