### ISSUE TITLE
Implement LetsDoCoinz Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#797]
https://letsdocoinz.com/
https://letsdocoinz.com/api/

**Comment by nomanurrehman** [comment]
The documentation only shows a ticker endpoint so we only need to implement a ticker for this one?

**Comment by estherleongym** [comment]
@nomanurrehman if we can only find API endpoints for ticker then yep, just implement what you're able to at the moment.

**Comment by nomanurrehman** [comment]
@estherleongym Got it. Thanks!

**Comment by nomanurrehman** [comment]
I am not working on this one anymore.

**Comment by TJ-CoinGecko** [comment]
https://letsdocoinz.com/api/2/public/ticker/

**Comment by LetsDoCoinz** [comment]
Please send us your server IP address and we will add it to our Whitelist (office@letsdocoinz.com)

**Comment by estherleongym** [comment]
@TJ-CoinGecko I'll take this and email them the IP addresses to whitelist

**Comment by estherleongym** [comment]
@LetsDoCoinz I've emailed to the email address provided.

**Comment by LetsDoCoinz** [comment]
We move ticker API, now it was without IP protection http://api.letsdocoinz.com/ticker
