### ISSUE TITLE
Implement IQFinex Exchange Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#816]
https://www.iqfinex.com/
https://api.iqfinex.com/

**Comment by Swingcloud** [comment]
let me do this

**Comment by Swingcloud** [comment]
I can't find ticker info, wrote an email to ask them can provide or not

**Comment by TJ-CoinGecko** [comment]
@Swingcloud any updates from them? This is the email from the form that they just submitted again: info@iqfinex.com
