### ISSUE TITLE
Implement CoinZest Exchange Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#820]
https://www.coinzest.co.kr
https://api.coinzest.co.kr

**Comment by Swingcloud** [comment]
can't link to their api doc, will try it sometime

**Comment by coinzest** [comment]
Hello, I'm the person in charge from CoinZest.
Could you suggest any specific reason for the problem?
If it is the translation problem, we can provide the english manual.

**Comment by Swingcloud** [comment]
hello @coinzest, seems I can't go into this api link https://api.coinzest.co.kr, when I click it it just keep connecting then went timeout,  is there other place I can get an api doc?

**Comment by coinzest** [comment]
Hi Sam,
We talked to our developers, and they said that the API address was built
to form a firewall from outside the security.
Access is limited to certain IP allowed by the administrator.
Therefore, if you enter your IP address, you will be able to approve access
to the developer immediately.

Thank you.


2018-08-14 12:31 GMT+09:00 Sam Lin <notifications@github.com>:

**Comment by Swingcloud** [comment]
https://api.coinzest.co.kr/api/public/market_summary

**Comment by estherleongym** [comment]
I'll take this

**Comment by great9** [comment]
the api docs are non-existant. why?
