### ISSUE TITLE
Implement Bitmax Exchange Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#827]
https://github.com/bitmax-exchange/api-doc
https://bitmax.io/

Please be aware that BitMax.io’s new website will go live on August 10th, 2018 at 5:00 PM EST. New user registrations, deposits, and withdrawals will be available at the launch. Users will also be able to submit KYC documents, and your previous accounts will still be valid with the new website. 

Please also note that trading features will be available on August 13th, 2018 at 9:00 AM EST. BitMax.io’s mining features will not be available on 13th. Please stay tuned for further notices. 
 
The following 11 coins/tokens will be available for trading; 
BTC, BCH, ETH, LTC, USDT, IOST, LBA, LFT, OLT, SEELE, ZIL.

The below are the trading pairs that will be offered at launch; 
BCH/BTC, ETH/BTC, LTC/BTC, IOST/BTC, LBA/BTC, LFT/BTC, OLT/BTC, SEELE/BTC, ZIL/BTC, BCH/ETH, LTC/ETH, IOST/ETH, LBA/ETH, LFT/ETH, OLT/ETH, SEELE/ETH, ZIL/ETH, BTC/USDT, ETH/USDT.

**Comment by Swingcloud** [comment]
Let me take this
