### ISSUE TITLE
JSON::ParserError in the function of <List market pairs supported by an exchange>

### ISSUE THREAD

**Issue by ghost** [coingecko/cryptoexchange#832]
Hi team,

An JSON::ParserError makes the function of  <List market pairs supported by an exchange> not work. Please help to fix it. Thank you very much.

The test code is:
require 'cryptoexchange'
client = Cryptoexchange::Client.new
client.exchange_for('btc')

>> Changes made for Debug:
diff --git a/lib/cryptoexchange/services/pairs.rb b/lib/cryptoexchange/services/pairs.rb
index 809f605..0bfd1d7 100644
--- a/lib/cryptoexchange/services/pairs.rb
+++ b/lib/cryptoexchange/services/pairs.rb
@@ -21,6 +21,11 @@ module Cryptoexchange

       def fetch_via_api(endpoint = self.class::PAIRS_URL, params = self.class::POST_PARAMS)
         begin
+          print "endpoint: "
+          puts endpoint
+          print "params: "
+          puts params

>> The final error is:
endpoint: https://api.abcc.com/api/v2/tickers.json
params:
endpoint: https://api.abucoins.com/products
params:
endpoint: https://acx.io/api/v2/markets.json
params:
endpoint: https://api.aex.com/ticker.php?c=all&mk_type=btc
params:
endpoint: https://api.aex.com/ticker.php?c=all&mk_type=bitcny
params:
endpoint: https://api.aex.com/ticker.php?c=all&mk_type=bitusd
params:
Traceback (most recent call last):
	9: from exchange_for.rb:3:in `<main>'
	8: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/client.rb:46:in `exchange_for'
	7: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/client.rb:46:in `each'
	6: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/client.rb:47:in `block in exchange_for'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/client.rb:17:in `pairs'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/exchanges/aex/services/pairs.rb:12:in `fetch'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/exchanges/aex/services/pairs.rb:12:in `map'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/exchanges/aex/services/pairs.rb:13:in `block in fetch'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/services/pairs.rb:22:in `fetch_via_api'
/usr/local/lib/ruby/gems/2.5.0/gems/cryptoexchange-0.23.0/lib/cryptoexchange/services/pairs.rb:42:in `rescue in fetch_via_api': {:error=>#<JSON::ParserError: 765: unexpected token at 'invalid_pricing_coin'>, :response=>#<HTTP::Response/1.1 200 OK {"Date"=>"Sat, 11 Aug 2018 04:18:31 GMT", "Content-Type"=>"application/json; charset=utf-8", "Transfer-Encoding"=>"chunked", "Connection"=>"close", "Vary"=>"Accept-Encoding", "Pragma"=>"no-cache", "Cache-Control"=>"no-cache,must-revalidate", "X-Cdn-Edge"=>"1932895,-", "Set-Cookie"=>"__cdnuid=90b540e6eb849f4977c93516ee2f6c76; max-age=31536000; path=/; HttpOnly", "X-Cache"=>"bypass"}>} (Cryptoexchange::JsonParseError)

**Comment by xiaobingo** [comment]
Apparently, the error comes from the handling of endpoint: https://api.aex.com/ticker.php?c=all&mk_type=bitusd
