### ISSUE TITLE
Implement Bitkub Exchange Ticker, Orderbook, Trades

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#840]
Exchange’s Website: www.bitkub.com
API Document: https://github.com/bitkub/bitkub-official-api-docs
API Price ticker: https://api.bitkub.com/api/market/ticker

**Comment by Swingcloud** [comment]
I'll do this

**Comment by tmlee** [comment]
@Swingcloud whats the status on this exchange like? any blockers?

**Comment by Swingcloud** [comment]
sorry just not finished yet 🙈
