### ISSUE TITLE
Implement AXNET Exchange

### ISSUE THREAD

**Issue by superdev810** [coingecko/cryptoexchange#879]
https://ax.net/api/returnTicker?market=ETH_BTC
https://ax.net/api/return24Trades?market=ETH_BTC
https://ax.net/api/return24Orderbook?market=ETH_BTC

**Comment by bobbyong** [comment]
https://dex.ax.net
https://dexapi.ax.net/public/?command=returnTicker
Docs: https://github.com/AX-NET/dex-api-docs/

**Comment by superdev810** [comment]
It's just dex
We have centralized and decentralized exchange combined.
https://ax.net/api/returnTicker

**Comment by tmlee** [comment]
Then 3 original endpoints dont seem to work anymore, which is what this module is written based on.

Need to be updated to use the returnTicker endpoint

**Comment by superdev810** [comment]
Yup
I'm gonna update the returnTicker

**Comment by tmlee** [comment]
@superdev810 sure, let me know how that goes or when you are ready

**Comment by superdev810** [comment]
https://ax.net/api/returnTicker?market=ETH_BTC
https://ax.net/api/returnTicker
https://ax.net/api/return24Trades?market=ETH_BTC
https://ax.net/api/return24Orderbook?market=ETH_BTC

It's done
@tmlee 
Pls check it

**Comment by superdev810** [comment]
@bobbyong even our these 4 apis are working fine now, but showing volume is zero.
what issue for now?
