### ISSUE TITLE
basevolume is not for base 

### ISSUE THREAD

**Issue by Swingcloud** [coingecko/cryptoexchange#88]
@tmlee found that in Cryptopia ticker api, basevolume not respond base to us instead of volume, so we need to check if other api send the wrong volume to us too

**Comment by dominicwong617** [comment]
- [] anx
- [] bitcoin_indonesia
- [] bitfinex
- [] bitflyer
- [] bithumb
- [] bitstamp
- [] bittrex
- [] bleutrade
- [] btcc
- [] bter
- [] ccex
- [] chbtc
- [] coin_exchange
- [] coincheck
- [] coinone
- [] cryptopia
- [] ether_delta
- [] gatecoin
- [] gdax
- [] gemini
- [] hitbtc
- [] jubi
- [] korbit
- [] kraken
- [] lakebtc
- [] liqui
- [] livecoin
- [] novaexchange
- [] okcoin
- [] poloniex
- [] quoine
- [] viabtc
- [] yobit
- [] yunbi

**Comment by Swingcloud** [comment]
anx
bitcoin_indonesia
bitfinex
bitflyer
bithumb
bitstamp
bittrex
bleutrade
btcc
bter
ccex
chbtc
coin_exchange
coincheck
coinone
cryptopia
ether_delta
gatecoin
gdax
gemini
hitbtc
jubi
korbit
kraken
lakebtc - correct
liqui - correct
livecoin - correct
novaexchange - correct
okcoin - correct
poloniex - use quoteVolume
quoine - correct
viabtc - correct
yobit - correct
yunbi - correct

**Comment by mmplisskin** [comment]
@Swingcloud There seems to be an issue with this on lykke.
