### ISSUE TITLE
Implement Coindirect

### ISSUE THREAD

**Issue by bobbyong** [coingecko/cryptoexchange#916]
https://www.coindirect.com
https://coindirect.docs.stoplight.io

**Comment by Swingcloud** [comment]
let me do this

**Comment by Swingcloud** [comment]
on their API doc that https://coindirect.docs.stoplight.io/exchange/api/historical-data/gethistoricalexchangetrades can get high and low on pairs, but they didn't write what do I need to put in history query part, write a letter to ask them, or just implement other data like ask, bids, volume...
 on this endpoint https://api.coindirect.com/api/v1/exchange/market

**Comment by bobbyong** [comment]
@Swingcloud heard back from Coindirect

Regarding the format for the query parameter, here is an example: https://api.coindirect.com/api/v1/exchange/historical/trades/BTC-ZAR/24h
