### ISSUE TITLE
Implement Airswap exchange

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#926]
Airswap.io/trade
https://github.com/airswap/developers/tree/master/api-server
support@airswap.io

**Comment by Swingcloud** [comment]
I think we can use this endpoint to fetch ticker's info: https://maker-stats.production.airswap.io/ticker

**Comment by TJ-CoinGecko** [comment]
You can try to contact them directly with this email: jay.kurahashisofue@fluidity.io

**Comment by wenjieyek** [comment]
I will do this

**Comment by wenjieyek** [comment]
https://github.com/coingecko/cryptoexchange/pull/984
