### ISSUE TITLE
Implement ChainEX

### ISSUE THREAD

**Issue by TJ-CoinGecko** [coingecko/cryptoexchange#933]
https://chainex.io/
https://chainex.io/api/v1

**Comment by depach** [comment]
I basically have this finished, except I have  2 questions:

- Api shows volume in `target` not `base` , is it acceptable to use the price to covert to the `base`?
- Api currently has no trade id, is this required?

**Comment by Swingcloud** [comment]
hello @depach 
- if the volume is in target, basically we will divide it by `last` to let it target to `base` volume
- if trades doesn't have trade id, then can just ignore it for now

**Comment by depach** [comment]
@Swingcloud thanks, I will submit a pull request soon

They are looking at adding the base volume at a later stage, then I can update the integration
