### ISSUE TITLE
HitBTC Ticker Timestamp may be incorrect

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#94]

**Comment by Swingcloud** [comment]
@tmlee HitBTC's timestamps send 13 digit (like: 1503382216609) instead 10 digit, maybe we just remove the last 3 digit?

**Comment by tmlee** [comment]
Yeah it is in miliseconds, removing the last 3 digits works too
But i think `Time.strptime(milliseconds.to_s, '%Q')` is more accurate

**Comment by Swingcloud** [comment]
HitBTC respond milliseconds, so I will just devide 1000

**Comment by tmlee** [comment]
Right, @Swingcloud no worries i pushed a hotfix here https://github.com/coingecko/cryptoexchange/commit/fa10996c47f89fc868e2988a5a81238b037238dc

**Comment by Swingcloud** [comment]
and this is also wrong too, I'll fix in the same PR
- bithumb
- btcc
- chbtc
- gemini
- tidex
- viabtc
