### ISSUE TITLE
Add missing trade_page_url to exchanges (Part B)

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#991]
In reference to 
- https://github.com/coingecko/cryptoexchange/blob/master/lib/cryptoexchange/exchanges/binance/market.rb#L7
- https://github.com/coingecko/cryptoexchange/blob/master/spec/exchanges/binance/integration/market_spec.rb#L20
- Label the exchange in the README when implemented

add trade_page_url to list of the following exchanges
- [ ] Bit-Z
- [ ] Bitbay
- [ ] BitBNS
- [ ] Bitcoin Indonesia (Indodax)
- [ ] Bitfinex
- [ ] Bitflyer
- [ ] Bitforex
- [ ] Bithumb

If not available, put the root url of the exchange

**Comment by Nirajn2311** [comment]
Can I take this up?

**Comment by yihyang** [comment]
@tmlee I will take this up
