### ISSUE TITLE
Add missing trade_page_url to exchanges (Part E)

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#998]
In reference to 
- https://github.com/coingecko/cryptoexchange/blob/master/lib/cryptoexchange/exchanges/binance/market.rb#L7
- https://github.com/coingecko/cryptoexchange/blob/master/spec/exchanges/binance/integration/market_spec.rb#L20
- Label the exchange in the README when implemented

add trade_page_url to list of the following exchanges
- [ ] LakeBTC
- [ ] Luno
- [ ] MaxMaicoin
- [ ] Poloniex
- [ ] Quoine (Liquid)
- [ ] Yobit
- [ ] Tidebit
- [ ] Dobitrade

**Comment by estherleongym** [comment]
I'll take this
